### PR TITLE
Fix for Categories/Genres and "Öppet Arkiv"

### PR DESCRIPTION
**Pull request by JeppeTh**

### CODE REVIEW

**Comment by kalle77** [comment]
Seems like this doesnt work if the program only has one episode, for example Genrer->Dokumentär->104 dagar. Then no video is presented, works fine for other shows where there are multiple episodes.
Regards,
Kalle

**Comment by JeppeTh** [comment]
First of all I don't think this fix has anything to do with this.  Then it seems Svtplay behaves strange, 104 is an episode of "Dokumentärfilm" and shouldn't appear amongst "A-Ö". Not sure I'll do anything about this... I'll have a look later on.

**Comment by JeppeTh** [comment]
It seems easy to fix - so I hopefully did - new pull on its way.

**Comment by kalle77** [comment]
Great, thanks for quick response!

**Pull request merged**
