### PR TITLE
Corrections for #60, #59 and AddSections index handling

### LINKED ISSUE #59: Variable 'url' referenced before assignment
I'm getting `INFO (__init__:663) - JTDEBUG new summary failed:local variable 'url' referenced before assignment`
Don't know if this actually affects the application much, but when looking at the code it seems simple enough to fix this by moving the url assignment before accessing it.

### LINKED ISSUE #60: 'Populärast just nu' broken
When entering 'Populärast just nu' the log shows the following. This results in an error message on screen. I guess svtplay.se changed the pages a bit.

```
2015-10-22 22:31:58,189 (7f95d77fe700) :  DEBUG (runtime:717) - Handling request GET /video/svt/GetSectionEpisodes?index=0&prevTitle=SVT+Play&title
=Popul%C3%A4rast+just+nu
2015-10-22 22:31:58,190 (7f95d77fe700) :  DEBUG (runtime:49) - Received packed state data (500 bytes)
2015-10-22 22:31:58,192 (7f95d77fe700) :  DEBUG (runtime:814) - Found route matching /video/svt/GetSectionEpisodes
2015-10-22 22:31:58,193 (7f95d77fe700) :  DEBUG (networking:172) - Requesting 'http://www.svtplay.se'
2015-10-22 22:31:58,277 (7f95d77fe700) :  INFO (__init__:663) - JTDEBUG new summary failed:local variable 'url' referenced before assignment
2015-10-22 22:31:58,278 (7f95d77fe700) :  CRITICAL (runtime:883) - Exception (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Frame
work/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/SVT-Play.bundle/Contents/Code/__init__.py", line 146, in Ge
tSectionEpisodes
    oc = GetEpisodeObjects(oc, articles, showName=None)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/SVT-Play.bundle/Contents/Code/__init__.py", line 703, in Ge
tEpisodeObjects
    seasonInfo = re.sub("[      \n]*", "", seasonInfo[0].strip())
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Frame
work/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by baldervanx**
This closes #59 and closes #60. More importantly makes the contents of many items on the main menu become correct again by correcting the index handling in AddSections. Also removing some unecessary error printouts to log by replacing `try`-blocks with `if`-statements.

### CODE REVIEW

**Comment by sander1** [comment]
@meriko @JeppeTh Any chance you can have a look at this?

**Comment by meriko** [comment]
I don't think this is relevant anymore since this PR was made before the switch to use XML instead of webpage scraping? "Populärast" and main menu are working as expected in the current version.

**Comment by JeppeTh** [comment]
Yes - this can be skipped.

**Comment by sander1** [comment]
Cool! Thanks for looking into this!

**Pull request closed without merging**
